name: PulseView macOS build for ARM - Steps

on:
  workflow_call:
    inputs:
      artifact_version:
        required: false
        type: string
        default: "NIGHTLY"

outputs:
  pr_links:
    description: "Links to the artifacts for pull requests"
    value: ${{ steps.pr_links.outputs.PR_LINKS }}

env:
  TARGET: "arm"
  BREW_PYTHON_VERSION: "python@3"
  BREW_QT_VERSION: "qt"
  ARTIFACT_TITLE: "pulseview"
  ARTIFACT_BIN_NAME: "pulseview"
  ARTIFACT_VERSION: ${{ inputs.artifact_version }}

steps:
  - name: Set artifact version to PR
    if: (github.event_name == 'pull_request')
    run: |
      echo "ARTIFACT_VERSION=pr${{ github.event.pull_request.number }}" >> $GITHUB_ENV

  - name: Install dependencies
    run: |
      brew install autoconf automake autoconf-archive pkg-config libtool \
      libzip libusb libftdi hidapi nettle check doxygen swig \
      glib glibmm@2.66 cmake boost sdcc $BREW_PYTHON_VERSION $BREW_QT_VERSION

  - name: Checkout sigrok-build
    run: |
      git clone https://github.com/manobendro/sigrok-build.git

  - name: Build dependencies
    run: |
      cd sigrok-build/ci/macos
      source sigrok-macos-init-toolchain.sh
      ./sigrok-macos-build-dependencies.sh

  - name: Checkout sigrok's PulseView
    uses: actions/checkout@v4
    with:
      repository: sigrokproject/pulseview
      path: pulseview

  - name: Checkout PulseView from PR
    if: (github.event_name == 'pull_request')
    uses: actions/checkout@v4
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.ref }}
      path: pulseview
      fetch-depth: 0

  - name: Build PulseView
    run: |
      source sigrok-build/ci/macos/sigrok-macos-init-toolchain.sh
      mkdir -p pulseview/build
      cd pulseview/build
      PKG_CONFIG_PATH=$P cmake \
        -DCMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
        -DCMAKE_BUILD_TYPE=Debug \
        -DDISABLE_WERROR=FALSE \
        -DENABLE_TESTS=FALSE \
        ..
      make $PARALLEL $V
      make install $V

  - name: Build DMG
    run: |
      cd sigrok-build/ci/macos
      source sigrok-macos-init-toolchain.sh
      ./sigrok-macos-create-dmg.sh

  - name: Upload artifact
    id: upload
    uses: actions/upload-artifact@v4
    with:
      name: artifact-pulseview-arm-macos
      path: sigrok-build/ci/macos/pulseview*.dmg

  - name: Add artifact to pull request message
    id: pr_links
    if: (github.event_name == 'pull_request')
    run: |
      echo "PR_LINKS=[pulseview-${{ env.ARTIFACT_VERSION }}-${{ env.TARGET }}.dmg](${{ steps.upload.outputs.artifact-url }})" >> $GITHUB_OUTPUT